### ISSUE TITLE
hidden miner??

### ISSUE THREAD

**Issue by lnwc** [millerberto/CampManagement-API#2]
it's mining dogecoins

help

pls

**Comment by lnwc** [comment]
at least give the dogecoins to me

**Comment by lnwc** [comment]
el frogo popo does not work

**Comment by lnwc** [comment]
the .exe file is all greasy and smells of processed potato product

**Comment by lnwc** [comment]
the developer is a fat bald man please help

**Comment by millerberto** [comment]
Come on now. You can check the source code for yourself.
